"""delete root id

Revision ID: 13298eb330c1
Revises: 7052ad2ddecb
Create Date: 2024-11-23 13:38:15.417479

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '13298eb330c1'
down_revision = '7052ad2ddecb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shared_posts', schema=None) as batch_op:
        batch_op.drop_constraint('shared_posts_ibfk_3', type_='foreignkey')
        batch_op.drop_column('root_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shared_posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('root_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('shared_posts_ibfk_3', 'posts', ['root_id'], ['post_id'])

    # ### end Alembic commands ###
