"""added a shared model

Revision ID: 47e3e604bbbe
Revises: e85091daea63
Create Date: 2024-10-21 16:07:07.320321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47e3e604bbbe'
down_revision = 'e85091daea63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('root_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'posts', ['root_id'], ['post_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('root_id')

    # ### end Alembic commands ###
