"""Rename content to custtom_content in Share model

Revision ID: 56a854d52e46
Revises: 671ada35ac75
Create Date: 2024-11-22 11:25:37.352366

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '56a854d52e46'
down_revision = '671ada35ac75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shared_posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('custom_content', sa.Text(), nullable=True))
        batch_op.drop_column('content')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shared_posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content', mysql.TEXT(), nullable=False))
        batch_op.drop_column('custom_content')

    # ### end Alembic commands ###
