"""Add share_count and repost_count to Post

Revision ID: 671ada35ac75
Revises: 951d88738dec
Create Date: 2024-11-22 02:15:38.916882

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '671ada35ac75'
down_revision = '951d88738dec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('share_count', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('repost_count', sa.Integer(), nullable=False))

    with op.batch_alter_table('shared_posts', schema=None) as batch_op:
        batch_op.drop_column('repost_count')
        batch_op.drop_column('share_count')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shared_posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('share_count', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('repost_count', mysql.INTEGER(), autoincrement=False, nullable=False))

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('repost_count')
        batch_op.drop_column('share_count')

    # ### end Alembic commands ###
