"""add root id

Revision ID: 7052ad2ddecb
Revises: 56a854d52e46
Create Date: 2024-11-23 13:24:26.712402

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7052ad2ddecb'
down_revision = '56a854d52e46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_constraint('posts_ibfk_2', type_='foreignkey')
        batch_op.drop_column('root_id')

    with op.batch_alter_table('shared_posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('root_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'posts', ['root_id'], ['post_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shared_posts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('root_id')

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('root_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('posts_ibfk_2', 'posts', ['root_id'], ['post_id'])

    # ### end Alembic commands ###
