"""Add share_count and repost_count to Post

Revision ID: 951d88738dec
Revises: c872cb5d08c6
Create Date: 2024-11-22 02:00:08.389774

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '951d88738dec'
down_revision = 'c872cb5d08c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('share_count')
        batch_op.drop_column('repost_count')

    with op.batch_alter_table('shared_posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('share_count', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('repost_count', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shared_posts', schema=None) as batch_op:
        batch_op.drop_column('repost_count')
        batch_op.drop_column('share_count')

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('repost_count', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('share_count', mysql.INTEGER(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
