"""Add share_count and repost_count to Post

Revision ID: c872cb5d08c6
Revises: 3e47c1075fd5
Create Date: 2024-11-21 22:53:22.547072

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c872cb5d08c6'
down_revision = '3e47c1075fd5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('share_count', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('repost_count', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('repost_count')
        batch_op.drop_column('share_count')

    # ### end Alembic commands ###
